apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-web
  name: simple-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
